### ISSUE TITLE
Removing `gcc` package

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/bob.io.base-feedstock#5]
We now have a C++11 capable `gcc` compiler in the docker image. It would be nice if you could do the following to try this.
1. Fork this repo.
2. Create a new branch
3. Remove `gcc` and `libgcc`.
4. Add, commit, push to your fork.
5. Open a PR to remove them.
6. Note in the PR that this issue is fixed by it.

Please ping me when you have done these things.

**Comment by 183amir** [comment]
I better automate this.
